module.exports = () => ({
  name: 'Botali',
  slug: 'botali',
  version: '1.0.0',
  orientation: 'portrait',
  icon: './assets/icon.png',
  scheme: 'botali',
  userInterfaceStyle: 'automatic',
  plugins: [
    ['expo-location', {
      locationWhenInUsePermission: 'O Botali usa sua localização para mostrar postos e preços próximos.',
      locationAlwaysAndWhenInUsePermission: 'O Botali usa geofences para reconhecer visitas a postos e sugerir confirmações úteis, mesmo com o app fechado.',
      isAndroidBackgroundLocationEnabled: true,
      isIosBackgroundLocationEnabled: true,
    }],
    'expo-notifications',
    'expo-font',
    ['expo-splash-screen', {
      backgroundColor: '#F7F7F5',
      image: './assets/splash-icon.png',
      imageWidth: 180,
      dark: { backgroundColor: '#111111', image: './assets/splash-icon.png' },
    }],
  ],
  ios: {
    supportsTablet: true,
    bundleIdentifier: 'com.botali.app',
    icon: { light: './assets/icon-light.png', dark: './assets/icon-dark.png' },
    infoPlist: {},
  },
  android: {
    adaptiveIcon: { backgroundColor: '#171717', foregroundImage: './assets/android-icon-foreground.png', monochromeImage: './assets/android-icon-monochrome.png' },
    predictiveBackGestureEnabled: false,
    package: 'com.botali.app',
    permissions: [
      'ACCESS_COARSE_LOCATION',
      'ACCESS_FINE_LOCATION',
      'ACCESS_BACKGROUND_LOCATION',
      'android.permission.ACCESS_COARSE_LOCATION',
      'android.permission.ACCESS_FINE_LOCATION',
      'android.permission.ACCESS_BACKGROUND_LOCATION',
      'android.permission.FOREGROUND_SERVICE',
      'android.permission.FOREGROUND_SERVICE_LOCATION',
    ],
    config: { googleMaps: { apiKey: process.env.GOOGLE_MAPS_ANDROID_API_KEY ?? '' } },
  },
  web: { favicon: './assets/favicon.png' },
  extra: { eas: { projectId: 'fc640c3a-b4f6-411c-84c7-511dc68b7626' } },
});
