module.exports = () => ({
  name: 'Botali',
  slug: 'botali',
  owner: 'ningas',
  description: 'Encontre postos próximos, compare preços da comunidade e escolha com mais confiança.',
  version: '1.0.0',
  orientation: 'portrait',
  icon: './assets/icon.png',
  scheme: 'botali',
  userInterfaceStyle: 'automatic',
  runtimeVersion: { policy: 'appVersion' },
  updates: {
    url: 'https://u.expo.dev/fc640c3a-b4f6-411c-84c7-511dc68b7626',
    checkAutomatically: 'ON_LOAD',
    fallbackToCacheTimeout: 0,
  },
  plugins: [
    ['expo-location', {
      locationWhenInUsePermission: 'O Botali usa sua localização para mostrar postos e preços próximos.',
      locationAlwaysAndWhenInUsePermission: 'O Botali usa geofences para reconhecer visitas a postos e sugerir confirmações úteis, mesmo com o app fechado.',
      isAndroidBackgroundLocationEnabled: true,
      isIosBackgroundLocationEnabled: true,
    }],
    'expo-notifications',
    'expo-font',
    ['expo-splash-screen', {
      backgroundColor: '#F7F7F5',
      image: './assets/splash-icon.png',
      imageWidth: 180,
      dark: { backgroundColor: '#111111', image: './assets/splash-icon.png' },
    }],
  ],
  ios: {
    supportsTablet: true,
    bundleIdentifier: 'com.botali.app',
    icon: { light: './assets/icon-light.png', dark: './assets/icon-dark.png' },
    config: { googleMapsApiKey: process.env.GOOGLE_MAPS_IOS_API_KEY ?? '' },
    infoPlist: {},
  },
  android: {
    adaptiveIcon: { backgroundColor: '#171717', foregroundImage: './assets/android-icon-foreground.png', monochromeImage: './assets/android-icon-monochrome.png' },
    predictiveBackGestureEnabled: false,
    package: 'com.botali.app',
    config: { googleMaps: { apiKey: process.env.GOOGLE_MAPS_ANDROID_API_KEY ?? '' } },
  },
  web: { favicon: './assets/favicon.png' },
  extra: { eas: { projectId: 'fc640c3a-b4f6-411c-84c7-511dc68b7626' } },
});
